# Generated by Django 5.0.6 on 2024-07-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas', to='vehiculos.marca')),
            ],
        ),
    ]
