# Generated by Django 5.0.6 on 2024-07-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_pais_auto_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
